# Docker Compose

version: '3'

services:
  web:
    container_name: movies-web-app
    image: movies:0.0.1-SNAPSHOT
    networks:
      - movie-app
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  mongo:
    container_name: movies-mongo-db
    networks:
      - movie-app
    image: mongo:latest
    volumes:
      - data:/data
    ports:
      - "27017:27017"
volumes:
  data: {}

networks:
  movie-app:
    driver: bridge
