### POST-CREATE-MOVIE-INFO 1
POST http://localhost:8081/v1/movieinfos
Content-Type: application/json

{
  "movieInfoId": 1,
  "name": "Batman Begins",
  "year": 2005,
  "cast": ["Christian Bale", "Michael Cane"],
  "release_date": "2005-06-15"
}

### POST-CREATE-MOVIE-INFO 2
POST http://localhost:8081/v1/movieinfos
Content-Type: application/json

{
  "movieInfoId": 2,
  "name": "The Dark Knight",
  "year": 2008,
  "cast": ["Christian Bale", "HeathLedger"],
  "release_date": "2008-07-18"
}

### POST-CREATE-MOVIE-INFO 3
POST http://localhost:8081/v1/movieinfos
Content-Type: application/json

{
  "movieInfoId": null,
  "name": "Dark Knight Rises",
  "year": 2012,
  "cast": ["Christian Bale", "Tom Hardy"],
  "release_date": "2012-07-20"
}

### POST-REVIEW-1
POST http://localhost:8082/v1/reviews
Content-Type: application/json

{ "reviewId": 1, "movieInfoId": 1, "comment": "Excellent Movie", "rating": 8.0 }

### POST-REVIEW-2
POST http://localhost:8082/v1/reviews
Content-Type: application/json

{ "reviewId": 2, "movieInfoId": 2, "comment": "Excellent Movie", "rating": 8.0 }

### POST-REVIEW-3
POST http://localhost:8082/v1/reviews
Content-Type: application/json

{ "reviewId": null, "movieInfoId": 1, "comment": "Awesome Movie", "rating": 9.0 }

### GET-ALL-REVIEWS-FIND-BY-MOVIE-ID
GET http://localhost:8080/v1/movies/1

### GET-ALL-MOVIES-INFO-FIND-BY-STREAM
GET http://localhost:8080/v1/movies/info/stream
