spring:
  application:
    name: study-spring-reactive
  jpa:
    hibernate:
      ddl-auto: create
  docker:
    compose:
      stop:
        command: down
        timeout: 1m

---

spring:
  config:
    activate:
      on-profile: prod
  docker:
    compose:
      enabled: false
