spring:
  application:
    name: movies
  jpa:
    hibernate:
      ddl-auto: create
  docker:
    compose:
      stop:
        command: down
        timeout: 1m
      skip:
        in-tests: false
modules:
  movies:
    url: http://localhost:8080
  movies-info:
    url: http://localhost:8081
  movies-review:
    url: http://localhost:8082

---

spring:
  config:
    activate:
      on-profile: prod
  docker:
    compose:
      enabled: false
modules:
  movies:
    url: http://movies:8080
  movies-info:
    url: http://movies-info:8081
  movies-review:
    url: http://movies-review:8082

---

spring:
  config:
    activate:
      on-profile: test
  docker:
    compose:
      file: ../docker-compose.yml

logging:
  level:
    root: debug
